# site settings
title: Kaitlin Throgmorton
subtitle: MLIS
email: kaitlin@kaitlinthrogmorton.com
description: data librarian promoting data access and literacy </br> for everybody through teaching, research, and code. 
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
facebook_url:
github_url: https://github.com/kthrog
gitlab_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/kthrog/
pinterest_url:
slack_url:
twitter_url: 
goodreads_url: 


# build settings
markdown: kramdown

sass:
  style: compressed
